### ISSUE TITLE
macOS - wrong Minecraft install directory

### ISSUE THREAD

**Issue by Brogramming-Inc** [Brogramming-Inc/Minebrew#2]
Current behavior: `mbrew install mod-name` creates a new folder '.minecraft' in home directory and performs install actions in it

Desired behavior: `mbrew install mod-name` performs actions in ~/Library/Application\ Support/minecraft/

**Comment by nmandrus1** [comment]
Added a new `#[cfg(target_os = "macos")]` attribute for the get_mc_dir() function. Will test in the coming days to make sure its fixed
